//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isaac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isaac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000.
        /// </summary>
        internal static string rands64 {
            get {
                return ResourceManager.GetString("rands64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c9d3bc51 5bc24339 23e22e3a 5659b89a 21c6dcfd 168e10a4 1df755f6 99d3a910 
        ///f48f0656 e9431f57 839c384b 238bac78 d3693e2a 96e06a6f 1358bb9e 6872ff7f 
        ///75f9a391 9d951a6f 4460a8a1 2818c604 459b44fc e4eeacbf b13edb9c 38f9a0c4 
        ///9b6c882d 44ddb798 6a02781b 464d8241 b6e89c5b ee627b94 4b5cf183 030800c9 
        ///63e24cba 9582bdaa 8b038c2c 5bcc29d7 ab4e8369 7874b242 1302a96d ec44d5cc 
        ///6cc59d03 9abc6857 ea100737 c567708f b25912b4 53899438 b33ba5c0 08d848bc 
        ///e32573ca 1190acf5 d015c2e7 be2f137f 2f059bb6 82ca6f0a 39172da5 9bcb3a5b 
        ///8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string randseed {
            get {
                return ResourceManager.GetString("randseed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000.
        /// </summary>
        internal static string randv64 {
            get {
                return ResourceManager.GetString("randv64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f650e4c8e448e96d98db2fb4f5fad54f433f1afbedec154ad837048746ca4f9a
        ///5de3743e88381097f1d444eb823cedb66a83e1e04a5f6355c744243325890e2e
        ///7452e31957161df638a824f3002ed71329f5544951c08d83d78cb99ea0cc74f3
        ///8f651659cbc8b7c2f5f71c6912ad6419e5792e1b860536b809b3ce98d45d6d81
        ///f3b2612917e38f8529cf72ce349947b0c998f9ffb5e13dae32ae2a2bf7cf814c
        ///8ebfa303cf22e0640b923200eca4d58aef53cec4d0f7b37d9c411a2affdf8a80
        ///b40e27bcb4d2f97644b89b08f37c71d51a70e7e90bdb9c3060dc5207b3c3f24b
        ///d7386806229749b54e232cd091dabc65a70e11018b87437e5781414fc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string randvect {
            get {
                return ResourceManager.GetString("randvect", resourceCulture);
            }
        }
    }
}
